name: psypy
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.7
  - pip
  - numpy
  - matplotlib
  - scipy
  - pandas
  - pyopengl
  - pillow
  - lxml
  - openpyxl
  - xlrd
  - configobj
  - pyyaml
  - gevent
  - msgpack-python
  - psutil
  - pytables
  - requests[security]
  - cffi
  - wxpython
  - cython
  - pyzmq
  - pyserial
  - pysoundfile
  - python-bidi
  - moviepy
  - pyosf
  - greenlet==0.4.15
  - h5py
  - pip:
      # pyglet 1.4 isn't supported for psychopy yet
      # (https://github.com/psychopy/psychopy/issues/2518), and 1.3.2
      # is required for python 3.7 support
      # (https://bitbucket.org/pyglet/pyglet/issues/168/pyglettextdocument-fails-in-python-37-b1)
      - pyglet == 1.3.2
      - glfw
      - zmq
      - json-tricks
      - pyparallel
      - sounddevice
      - pygame
      - pysoundcard
      - psychopy_ext
      - psychopy == 3.1.5
