name: metamers
channels:
  - anaconda
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python==3.7
  - pip
  - ipykernel
  - scipy
  - seaborn
  - pandas
  - snakemake-minimal>=5.4
  - pyosf
  - imageio
  - scikit-image
  - pip:
      - pytest
      - torchvision
      - torch>=1.1
      - pyrtools>=0.9
      - parse
      # - plenoptic
