name: metamers
channels:
  - anaconda
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python==3.7
  - pip==19.1.1
  - ipykernel==5.1.1
  - scipy==1.2.1
  - seaborn==0.11
  - pandas==1.1.0
  - snakemake-minimal==5.5.3
  - pyosf==1.0.5
  - imageio==2.5.0
  - scikit-image==0.15.0
  - h5py==2.9.0
  - pip:
      - pytest==5.0.1
      - torchvision==0.5.0
      - torch==1.4
      - pyrtools==0.9.3
      - gputil==1.4.0
      - numpyro==0.5.0
      - arviz==0.11.1
      - funsor==0.4.0
      - tabulate==0.8.9
      - git+https://github.com/LabForComputationalVision/plenoptic.git@master
