name: tests
on:
  push:
  schedule:
    - cron: "0 0 * * 0" # weekly

jobs:
  test_models:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup conda
        uses: s-weigand/setup-conda@v1.0.5
        with:
          update-conda: true
          python-version: 3.7
          conda-channels: anaconda, conda-forge, bioconda
      - name: Create environment
        run: |
          conda env create -f environment.yml
          pip install git+https://github.com/LabForComputationalVision/plenoptic.git@binder
          pip install pytest
      - name: Run tests with pytest
        run: 'pytest tests/test_models.py'

  test_snakefile:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup conda
        uses: s-weigand/setup-conda@v1.0.5
        with:
          update-conda: true
          python-version: 3.7
          conda-channels: anaconda, conda-forge, bioconda
      - name: Create environment
        run: |
          conda env create -f environment.yml
          pip install git+https://github.com/LabForComputationalVision/plenoptic.git@master
      - name: Setup FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v1
      - name: Download data
        run: |
          mkdir -p data/metamers
          curl -O -J -L https://osf.io/4wyg3/download
          tar xf textures-subset-for-testing.tar.gz -C data
          rm textures-subset-for-testing.tar.gz
      - name: modify config.yml
        run: |
          sed -i 's/DATA_DIR:.*/DATA_DIR: "data/metamers"/g' config.yml
          sed -i 's|TEXTURE_DIR:.*|TEXTURE_DIR: "data/textures-subset-for-testing"|g' config.yml
      - name: run snakemake test
        run: |
          snakemake -j 5 -prk ~/Desktop/metamer_test/test_setup/RGC_norm_gaussian_gpu-0/einstein ~/Desktop/metamer_test/test_setup/V1_norm_s6_gaussian_gpu-0/einstein
