name: tests
on:
  push:
  schedule:
    - cron: "0 0 * * 0" # weekly

# see https://github.com/mamba-org/provision-with-micromamba#important
defaults:
  run:
    shell: bash -l {0}

jobs:
  test_models:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install conda environment with Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          extra-specs: python=3.7.1
      - name: Run tests with pytest
        run: |
          pytest tests/test_models.py

  test_snakefile:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install conda environment with Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          extra-specs: python=3.7.1
      - name: Setup FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v1
      - name: Download data
        run: |
          mkdir -p data/metamers/ref_images/
          curl -O -J -L https://osf.io/4wyg3/download
          tar xf textures-subset-for-testing.tar.gz -C data
          rm textures-subset-for-testing.tar.gz
      - name: modify config.yml
        run: |
          sed -i 's|DATA_DIR:.*|DATA_DIR: "data/metamers"|g' config.yml
          sed -i 's|TEXTURE_DIR:.*|TEXTURE_DIR: "data/textures-subset-for-testing"|g' config.yml
      - name: Run snakemake test
        run: |
          cp extra_packages/data/einstein.pgm data/metamers/ref_images/einstein_size-256,256.png
          snakemake -j 5 -prk data/metamers/test_setup/RGC_norm_gaussian_gpu-0/einstein data/metamers/test_setup/V1_norm_s6_gaussian_gpu-0/einstein

  run_Freeman_check_notebook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install conda environment with Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          extra-specs: python=3.7.1
      - name: Install extra requirements
        run: |
          mamba install jupyter nbconvert
      - name: modify config.yml
        run: |
          sed -i 's|DATA_DIR:.*|DATA_DIR: "data/metamers"|g' config.yml
          sed -i 's|TEXTURE_DIR:.*|TEXTURE_DIR: "data/textures-subset-for-testing"|g' config.yml
          mkdir -p data/metamers
          mkdir -p data/textures-subset-for-testing
      - name: Download data
        run : |
          source activate metamers
          snakemake -j 1 -prk download_freeman_check
      - name: run nbconvert
        run: |
          source activate metamers
          jupyter kernelspec list
          jupyter nbconvert --ExecutePreprocessor.kernel_name=python3 --to notebook --execute notebooks/Freeman_Check.ipynb
