name: tests
on:
  push:
  schedule:
    - cron: "0 0 * * 0" # weekly

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    name: tests
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup conda
        uses: s-weigand/setup-conda@v1.0.5
        with:
          update-conda: true
          python-version: 3.7
          conda-channels: anaconda, conda-forge, bioconda
      # - name: Checkout submodules
      #   uses: textbook/git-checkout-submodule-action@master
      - name: Create environment
        run: |
          conda env install -f environment.yml
          pip install git+https://github.com/LabForComputationalVision/plenoptic.git@master

  test_models:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Install extra requirements
        run: 'pip install pytest'
      - name: Run tests with pytest
        run: 'pytest tests/test_models.py'

  test_snakefile:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Setup FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v1
